services:
  es01:
    image: elasticsearch:8.12.1
    restart: unless-stopped
    env_file:
      - ./.env.es01
    volumes:
      - es01-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - mm-infra

  es02:
    image: elasticsearch:8.12.1
    restart: unless-stopped
    env_file:
      - ./.env.es02
    volumes:
      - es02-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es01
    networks:
      - mm-infra

  es03:
    image: elasticsearch:8.12.1
    restart: unless-stopped
    env_file:
      - ./.env.es03
    volumes:
      - es03-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es02
    networks:
      - mm-infra

  kibana:
    image: kibana:8.12.1
    restart: unless-stopped
    env_file:
      - ./.env.infra
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - mm-infra

volumes:
  es01-data:
  es02-data:
  es03-data:

networks:
  mm-infra:
    name: mm_infra_network
    driver: bridge
