services:
    manage-meals-app:
        image: ghcr.io/managemeals/manage-meals-api:latest
        restart: unless-stopped
        env_file:
            - ./.env
        depends_on:
            - mongo
            - redis
            - recipe-scraper
            - typesense
            - rabbitmq
            - queue-consumer
            - search-sync
            - webhooks-handler
        networks:
            - mmeals_net
