services:
  manage-meals-app-01:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - recipe-scraper-lb
      - typesense
      - rabbitmq
      - queue-consumer
      - search-sync
      - webhooks-handler
    networks:
      - mm-infra

  manage-meals-app-02:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - recipe-scraper-lb
      - typesense
      - rabbitmq
      - queue-consumer
      - search-sync
      - webhooks-handler
    networks:
      - mm-infra

  manage-meals-app-lb:
    image: haproxy:2.9
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    depends_on:
      - manage-meals-app-01
      - manage-meals-app-02
    volumes:
      - ./haproxy-manage-meals-app.cfg:/usr/local/etc/haproxy/haproxy.cfg
    env_file:
      - ./.env.docker
    networks:
      - mm-infra
