services:
    mongo:
        image: mongo:7
        restart: unless-stopped
        env_file:
            - ./.env.docker
        volumes:
            - mongo-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - mmeals_net

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        env_file:
            - ./.env.docker
        depends_on:
            - mongo
        networks:
            - mmeals_net

    redis:
        image: redis:7
        restart: unless-stopped
        networks:
            - mmeals_net

    recipe-scraper:
        image: ghcr.io/managemeals/manage-meals-scraper:latest
        restart: unless-stopped
        env_file:
            - ./.env.docker
        depends_on:
            - redis
        networks:
            - mmeals_net

    typesense:
        image: typesense/typesense:0.25.2
        restart: unless-stopped
        volumes:
            - typesense-data:/data
        env_file:
            - ./.env.docker
        networks:
            - mmeals_net

    rabbitmq:
        image: rabbitmq:3-management
        restart: unless-stopped
        env_file:
            - ./.env.docker
        networks:
            - mmeals_net

    queue-consumer:
        image: ghcr.io/managemeals/manage-meals-consumer:latest
        restart: unless-stopped
        env_file:
            - ./.env.docker
        depends_on:
            - rabbitmq
            - mongo
            - typesense
        networks:
            - mmeals_net

    search-sync:
        image: ghcr.io/managemeals/manage-meals-search-sync:latest
        restart: unless-stopped
        env_file:
            - ./.env.docker
        depends_on:
            - mongo
            - typesense
        networks:
            - mmeals_net

    webhooks-handler:
        image: ghcr.io/managemeals/manage-meals-webhooks-handler:latest
        restart: unless-stopped
        env_file:
            - ./.env.docker
        depends_on:
            - mongo
        networks:
            - mmeals_net

volumes:
    mongo-data:
    typesense-data:

networks:
    mmeals_net:
        name: mmeals_net
        driver: bridge
