name: Build and Push Docker Images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image: ghcr.io/managemeals/manage-meals-api
            dockerfile: Dockerfile
          - image: ghcr.io/managemeals/manage-meals-scraper
            dockerfile: scraper.Dockerfile
          - image: ghcr.io/managemeals/manage-meals-consumer
            dockerfile: consumer.Dockerfile
          - image: ghcr.io/managemeals/manage-meals-search-sync
            dockerfile: search-sync.Dockerfile
          - image: ghcr.io/managemeals/manage-meals-webhooks-handler
            dockerfile: webhooks-handler.Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ matrix.image }}:latest
